"""Added first_name and last_name

Revision ID: 7a7643ede752
Revises: 7aea538f842f
Create Date: 2026-08-22 14:49:53.152072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a7643ede752'
down_revision: Union[str, Sequence[str], None] = '7aea538f842f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('bookings', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('resources', 'type',
               existing_type=postgresql.ENUM('desk', 'room', name='enum_type'),
               type_=sa.Enum('desk', 'room', name='resourcetypeenum'),
               existing_nullable=False)
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'user', name='enum_role'),
               type_=sa.Enum('user', 'admin', name='userroleenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('user', 'admin', name='userroleenum'),
               type_=postgresql.ENUM('admin', 'user', name='enum_role'),
               existing_nullable=False)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.alter_column('resources', 'type',
               existing_type=sa.Enum('desk', 'room', name='resourcetypeenum'),
               type_=postgresql.ENUM('desk', 'room', name='enum_type'),
               existing_nullable=False)
    op.alter_column('bookings', 'end_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('bookings', 'start_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
